[features]
seeds = false
skip-lint = false
[programs.devnet]
spltokens = "C2eEY8eeediwD2YXvZZGQ74G9kPB5PeRNFGUzSiFadcW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/shivamsoni/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
